apiVersion: v1
kind: Secret
metadata:
  name: shared-credentials
type: Opaque
data:
  mongo-root-username: {{ .Values.auth.rootUsername | toString | b64enc | quote }}
  mongo-root-password: {{ .Values.auth.rootPassword | toString | b64enc | quote }}
