{{- $root := . }}
{{- range .Values.instances }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: {{ .name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        app.kubernetes.io/instance: {{ $root.Release.Name }}
    spec:
      containers:
        - name: mongo
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ $root.Values.auth.rootUsername | quote }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ $root.Values.auth.rootPassword | quote }}
            - name: MONGO_INITDB_DATABASE
              value: {{ $root.Values.auth.database | quote }}
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: {{ $root.Values.resources.requests.cpu | quote }}
              memory: {{ $root.Values.resources.requests.memory | quote }}
            limits:
              memory: {{ $root.Values.resources.limits.memory | quote }}
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ $root.Values.storage.className }}
      resources:
        requests:
          storage: {{ $root.Values.storage.size }}
{{- end }}
