apiVersion: v1
kind: Secret
metadata:
  name: shared-credentials
type: Opaque
data:
  mysql-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  mysql-user: {{ .Values.auth.username | b64enc | quote }}
  mysql-password: {{ .Values.auth.password | b64enc | quote }}